version: '1'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  queue:
    image: softwaremill/elasticmq:latest
    ports:
      - 9324:9324
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
networks:
  postgres: 
    driver: bridge
