version: '1'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
networks:
  postgres: 
    driver: bridge
